### ISSUE TITLE
Request for scraper

### ISSUE THREAD

**Issue by kotorichun77** [nus-cs3244-ml-singapore-7/hansard_data#1]
Hi, I'm a Singaporean civil servant working on a data project to analyse parliamentary questions and replies for work. I happened upon this project while trying to build my own scraper, and was wondering if you could guide me on how you scraped Hansard? I would like to scrape to an updated period (until 2023) and was hoping I could borrow your old code and update it myself. Looked through the files but the format_hansard file didn't seem to be the one scraping? Appreciate your response! I can also drop my private/work email if it's easier to communicate there. Thank you!

**Comment by nigelnnk** [comment]
Please feel free to reach out to me, preferably with your work email. My email is aaax [at] tngrpu.rqh after applying a [ROT13 transformation](https://rot13.com/).
